### PR TITLE
[election-api-js]: Use prettier for code formatting

### PR DESCRIPTION
**Pull request by paulbrimicombe**
## What?

Use `prettier` to automatically format code correctly in the JS API project (using the default `prettier` settings).

## Why?

It is a very common pattern to use `prettier` (and similar tools) to automatically format code in a consistent manner.  I have set it up to auto-format the project files when you run `npm test`.

## Notes

- This is somewhat a matter of taste so feel free to disagree with this change but please do give reasons if you do!
- I promise that I've not made any changes other than:
  - Installing `prettier`
  - Adding it to the `test` script in `package.json`
  - Running `npm test` to format all the code and run the tests

### CODE REVIEW

**Review by nicholasgriffintn — APPROVED** [review]
The code here is much nicer to read now and if the user has prettier installed as an extension, this should mean that it's easier for assessors to read while pairing as well.

**Comment by CameronWatt98** [comment]
It looks good. My only comment is that we use ESLint as a linter in our projects rather than Prettier. Is it worth considering this or are people generally happier with Prettier?

**Comment by paulbrimicombe** [comment]
> It looks good. My only comment is that we use ESLint as a linter in our projects rather than Prettier. Is it worth considering this or are people generally happier with Prettier?

Prettier and ESLint are different but related tools. The teams I work with actually use both — Prettier for formatting and ESLint for linting. My main concern here was around formatting which is why I opted to include Prettier (plus it works pretty well with the default configuration).

**Review by TimPerry — APPROVED** [review]
Very good, tested locally (i've setup some script to just call the endpoints and obvs run the tests). LGTM.

**Pull request merged**
