### PR TITLE
Remove async/await from the allCandidates code for consistency with PR #66

### PR DESCRIPTION
**Pull request by mattmouldbbc**

### CODE REVIEW

**Comment by njajones** [comment]
Whilst this is clearly an improvement, does it make sense to leave obvious errors in so that candidates can identify them? Perhaps listing them on the swift assessment paper doc so that assessors don't get caught out? I've had at least one candidate notice this and fix it during the assessment.

**Comment by mattmouldbbc** [comment]
Ah, hadn't realised the position of the errors were deliberate.

**Comment by njajones** [comment]
> Ah, hadn't realised the position of the errors were deliberate.

I'm not sure they are but they could be useful mistakes

**Comment by mattmouldbbc** [comment]
> > Ah, hadn't realised the position of the errors were deliberate.
> 
> I'm not sure they are but they could be useful mistakes

Fair. I've replaced 'em.

**Comment by njajones** [comment]
> > Ah, hadn't realised the position of the errors were deliberate.
> 
> I'm not sure they are but they could be useful mistakes

Ah, we are also talking about different things...... I meant the whole "leaving in async but not using it". One candidate picked up on the weirdness and it showed an understanding of async vs non-async

**Pull request merged**
